{
  #obtenerAeropuerto(id: "a9397b9d-ede6-434b-80ed-a451eda35148"){
  #  localizacion
  #rutas{
  #   fechaHoraSalida
  #   kilometros
  # }
  #}

  obtenerAeropuerto(localizacion: "Domenicafurt"){
    localizacion
    rutas{
      fechaHoraSalida
    }
  }
}